version: '2'
services:
    logvalue-app:
        image: logvalue
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://logvalue-postgresql:5432/LogValue
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    logvalue-postgresql:
        extends:
            file: postgresql.yml
            service: logvalue-postgresql
